service: serverless-cifar
 
provider:
  name: aws #cloud provider
  region: us-west-2 #region (oregon)
  memorySize: 3008 #memory usage
  timeout: 300 
 
functions:
  cifar:
    image: 884880583184.dkr.ecr.us-west-2.amazonaws.com/cifar-serverless-handson:latest
    events:
      - http:
          path: inference 
          method: post 
          cors: true